package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityBAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityBAllPropertiesEquals(EntityB expected, EntityB actual) {
        assertEntityBAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityBAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityBAllUpdatablePropertiesEquals(EntityB expected, EntityB actual) {
        assertEntityBUpdatableFieldsEquals(expected, actual);
        assertEntityBUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityBAutoGeneratedPropertiesEquals(EntityB expected, EntityB actual) {
        assertThat(expected)
            .as("Verify EntityB auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityBUpdatableFieldsEquals(EntityB expected, EntityB actual) {
        assertThat(expected)
            .as("Verify EntityB relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityBUpdatableRelationshipsEquals(EntityB expected, EntityB actual) {
        // empty method
    }
}
